package app.aaps.pump.omnipod.dash.history.database

import android.content.Context
import androidx.room.Room
import androidx.test.core.app.ApplicationProvider
import androidx.test.ext.junit.runners.AndroidJUnit4
import app.aaps.pump.omnipod.common.definition.OmnipodCommandType
import app.aaps.pump.omnipod.dash.history.data.BolusRecord
import app.aaps.pump.omnipod.dash.history.data.BolusType
import app.aaps.pump.omnipod.dash.history.data.InitialResult
import app.aaps.pump.omnipod.dash.history.data.ResolvedResult
import app.aaps.pump.omnipod.dash.history.data.TempBasalRecord
import com.google.common.truth.Truth.assertThat
import org.junit.After
import org.junit.Before
import org.junit.Test
import org.junit.runner.RunWith

/**
 * Instrumented tests for HistoryRecordDao — validates Room SQL queries,
 * TypeConverters, and entity persistence with a real in-memory database.
 */
@RunWith(AndroidJUnit4::class)
class HistoryRecordDaoTest {

    private lateinit var dao: HistoryRecordDao
    private lateinit var database: DashHistoryDatabase

    @Before
    fun setUp() {
        val context = ApplicationProvider.getApplicationContext<Context>()
        database = Room.inMemoryDatabaseBuilder(context, DashHistoryDatabase::class.java)
            .allowMainThreadQueries()
            .build()
        dao = database.historyRecordDao()
    }

    @After
    fun tearDown() {
        database.close()
    }

    private fun createEntity(
        id: Long = 0,
        date: Long = 1000L,
        commandType: OmnipodCommandType = OmnipodCommandType.SET_BASAL_PROFILE,
        createdAt: Long = System.currentTimeMillis()
    ) = HistoryRecordEntity(
        id = id,
        date = date,
        createdAt = createdAt,
        commandType = commandType,
        initialResult = InitialResult.NOT_SENT,
        tempBasalRecord = null,
        bolusRecord = null,
        basalProfileRecord = null,
        totalAmountDelivered = null,
        resolvedResult = null,
        resolvedAt = null
    )

    // --- save and all ---

    @Test
    fun save_assignsAutoGeneratedId() {
        val id = dao.save(createEntity()).blockingGet()
        assertThat(id).isGreaterThan(0L)
    }

    @Test
    fun save_multipleRecords_allRetrievable() {
        dao.save(createEntity()).blockingGet()
        dao.save(createEntity()).blockingGet()
        dao.save(createEntity()).blockingGet()

        val all = dao.all().blockingGet()
        assertThat(all).hasSize(3)
    }

    // --- first ---

    @Test
    fun first_emptyTable_returnsNull() {
        assertThat(dao.first()).isNull()
    }

    @Test
    fun first_populatedTable_returnsFirstById() {
        val id1 = dao.save(createEntity(date = 100)).blockingGet()
        dao.save(createEntity(date = 200)).blockingGet()
        val first = dao.first()
        assertThat(first).isNotNull()
        assertThat(first!!.id).isEqualTo(id1)
    }

    // --- byIdBlocking ---

    @Test
    fun byIdBlocking_existingRecord_returnsIt() {
        val id = dao.save(createEntity(date = 42)).blockingGet()
        val found = dao.byIdBlocking(id)
        assertThat(found).isNotNull()
        assertThat(found!!.date).isEqualTo(42L)
    }

    @Test
    fun byIdBlocking_missingRecord_returnsNull() {
        assertThat(dao.byIdBlocking(999L)).isNull()
    }

    // --- allSince ---

    @Test
    fun allSince_returnsOnlyRecordsAfterCutoff() {
        dao.save(createEntity(createdAt = 100)).blockingGet()
        dao.save(createEntity(createdAt = 200)).blockingGet()
        dao.save(createEntity(createdAt = 300)).blockingGet()

        val since250 = dao.allSince(250).blockingGet()
        assertThat(since250).hasSize(1)
        assertThat(since250[0].createdAt).isEqualTo(300)
    }

    @Test
    fun allSince_returnsRecordsAtExactCutoff() {
        dao.save(createEntity(createdAt = 200)).blockingGet()

        val since200 = dao.allSince(200).blockingGet()
        assertThat(since200).hasSize(1)
    }

    @Test
    fun allSince_orderedByCreatedAtDescending() {
        dao.save(createEntity(createdAt = 100)).blockingGet()
        dao.save(createEntity(createdAt = 300)).blockingGet()
        dao.save(createEntity(createdAt = 200)).blockingGet()

        val all = dao.allSince(0).blockingGet()
        assertThat(all.map { it.createdAt }).isEqualTo(listOf(300L, 200L, 100L))
    }

    // --- markResolved ---

    @Test
    fun markResolved_updatesResolvedFields() {
        val id = dao.save(createEntity()).blockingGet()
        dao.markResolved(id, ResolvedResult.SUCCESS, 5000L).blockingAwait()

        val record = dao.byIdBlocking(id)!!
        assertThat(record.resolvedResult).isEqualTo(ResolvedResult.SUCCESS)
        assertThat(record.resolvedAt).isEqualTo(5000L)
    }

    @Test
    fun markResolved_failure() {
        val id = dao.save(createEntity()).blockingGet()
        dao.markResolved(id, ResolvedResult.FAILURE, 6000L).blockingAwait()

        val record = dao.byIdBlocking(id)!!
        assertThat(record.resolvedResult).isEqualTo(ResolvedResult.FAILURE)
    }

    // --- setInitialResult ---

    @Test
    fun setInitialResult_updatesField() {
        val id = dao.save(createEntity()).blockingGet()
        dao.setInitialResult(id, InitialResult.SENT).blockingAwait()

        val record = dao.byIdBlocking(id)!!
        assertThat(record.initialResult).isEqualTo(InitialResult.SENT)
    }

    @Test
    fun setInitialResult_failureSending() {
        val id = dao.save(createEntity()).blockingGet()
        dao.setInitialResult(id, InitialResult.FAILURE_SENDING).blockingAwait()

        val record = dao.byIdBlocking(id)!!
        assertThat(record.initialResult).isEqualTo(InitialResult.FAILURE_SENDING)
    }

    // --- setTotalAmountDelivered ---

    @Test
    fun setTotalAmountDelivered_updatesField() {
        val id = dao.save(createEntity()).blockingGet()
        dao.setTotalAmountDelivered(id, 12.5).blockingAwait()

        val record = dao.byIdBlocking(id)!!
        assertThat(record.totalAmountDelivered).isEqualTo(12.5)
    }

    @Test
    fun setTotalAmountDelivered_nullValue() {
        val id = dao.save(createEntity()).blockingGet()
        dao.setTotalAmountDelivered(id, null).blockingAwait()

        val record = dao.byIdBlocking(id)!!
        assertThat(record.totalAmountDelivered).isNull()
    }

    // --- delete ---

    @Test
    fun delete_removesRecord() {
        val entity = createEntity()
        val id = dao.save(entity).blockingGet()
        val saved = dao.byIdBlocking(id)!!
        dao.delete(saved).blockingAwait()

        assertThat(dao.byIdBlocking(id)).isNull()
        assertThat(dao.all().blockingGet()).isEmpty()
    }

    // --- embedded records ---

    @Test
    fun save_withBolusRecord_roundtrips() {
        val entity = createEntity().copy(
            bolusRecord = BolusRecord(amout = 5.0, bolusType = BolusType.DEFAULT)
        )
        val id = dao.save(entity).blockingGet()
        val loaded = dao.byIdBlocking(id)!!
        assertThat(loaded.bolusRecord).isNotNull()
        assertThat(loaded.bolusRecord!!.amout).isEqualTo(5.0)
        assertThat(loaded.bolusRecord!!.bolusType).isEqualTo(BolusType.DEFAULT)
    }

    @Test
    fun save_withTempBasalRecord_roundtrips() {
        val entity = createEntity().copy(
            commandType = OmnipodCommandType.SET_TEMPORARY_BASAL,
            tempBasalRecord = TempBasalRecord(duration = 30, rate = 1.5)
        )
        val id = dao.save(entity).blockingGet()
        val loaded = dao.byIdBlocking(id)!!
        assertThat(loaded.tempBasalRecord).isNotNull()
        assertThat(loaded.tempBasalRecord!!.duration).isEqualTo(30)
        assertThat(loaded.tempBasalRecord!!.rate).isEqualTo(1.5)
    }

    @Test
    fun save_withBasalProfileRecord_roundtripsGsonSegments() {
        val segments = listOf(
            app.aaps.core.interfaces.profile.Profile.ProfileValue(0, 1.0),
            app.aaps.core.interfaces.profile.Profile.ProfileValue(3600, 0.5),
            app.aaps.core.interfaces.profile.Profile.ProfileValue(7200, 1.5)
        )
        val entity = createEntity().copy(
            basalProfileRecord = app.aaps.pump.omnipod.dash.history.data.BasalValuesRecord(segments)
        )
        val id = dao.save(entity).blockingGet()
        val loaded = dao.byIdBlocking(id)!!

        assertThat(loaded.basalProfileRecord).isNotNull()
        assertThat(loaded.basalProfileRecord!!.segments).hasSize(3)
        assertThat(loaded.basalProfileRecord!!.segments[0].timeAsSeconds).isEqualTo(0)
        assertThat(loaded.basalProfileRecord!!.segments[0].value).isEqualTo(1.0)
        assertThat(loaded.basalProfileRecord!!.segments[2].value).isEqualTo(1.5)
    }

    @Test
    fun save_withNullResolvedResult_roundtrips() {
        val entity = createEntity().copy(resolvedResult = null, resolvedAt = null)
        val id = dao.save(entity).blockingGet()
        val loaded = dao.byIdBlocking(id)!!
        assertThat(loaded.resolvedResult).isNull()
        assertThat(loaded.resolvedAt).isNull()
    }
}
